#https://www.mkdocs.org/user-guide/configuration/#
site_name: HEAL Data Utilities
site_url: https://heal.github.io/healdata-utils
repo_url: https://github.com/heal/healdata-utils
nav:
  - index.md
  # - contributing.md
  # - install.md
  - Variable Level Metadata:
    - vlmd/index.md
    - Functions:
      - Extract:
        - vlmd/extract/index.md
        - SAS dataset: vlmd/extract/sas.md
        - SPSS dataset: vlmd/extract/spss.md
        - Stata dataset: vlmd/extract/stata.md
        - Tabular (CSV) dataset: vlmd/extract/csvdata.md
        - REDCap export: vlmd/extract/redcapcsv.md
        - Frictionless Table Schema: vlmd/extract/frictionlessschema.md
        - Excel (xlsx) dataset: vlmd/extract/exceldata.md
      - Start:
        - vlmd/start/index.md
      - Validate:
        - vlmd/validate/index.md
    - Definitions:
      - Tabular (CSV) data dictionary: vlmd/schemas/csv-fields.md
      - JSON data dictionary: vlmd/schemas/json-data-dictionary.md
      
theme:
  name: material
  palette:
    scheme: heal_platform
  font:
    text: Montserrat
  logo: assets/HEAL_Initiative_White-cropped.svg
  features:
    - navigation.indexes
    # Disable for now, as it causes problems with links to sections in Safari
    # https://github.com/squidfunk/mkdocs-material/issues/3797
    # - navigation.instant
    - navigation.indexes
    #- navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    #- toc.integrate
  favicon: assets/heal_logo.png
extra_css:
  - stylesheets/extra.css
  - stylesheets/schema_doc.css
extra:
  homepage: https://heal.github.io/healdata-utils
use_directory_urls: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: True
      baselevel: 1
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  # - mkdocs-video:
  #     is_video: True

# TODO: add footer (this may be included in the custom jinja template?)
#    [![](img/gen3.png)](https://ctds.uchicago.edu/gen3)[![](img/createdby.png)](https://ctds.uchicago.edu/)
#   [![image alt text](image URL link)](anchor link)

# function readMore() { var dots = document.getElementById("dots"); var moreText = document.getElementById("more"); var btnText = document.getElementById("read-more-btn"); var btnText = document.getElementById("read-more-explorer"); if (dots.style.display === "none") { dots.style.display = "inline"; btnText.innerHTML = "Read more"; moreText.style.display = "none"; } else { dots.style.display = "none"; btnText.innerHTML = "Read less"; moreText.style.display = "inline"; } }
