name: Bundle CLI

on:
  push:
    tags:
      - "*"
jobs:

  bundle:
    name: Bundle cli for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    needs: release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Bundle CLI
      run: |
        pyinstaller scripts/vlmd.spec
    - name: Zip exe
      run: |
        python -m zipfile -c healdata-utils-${{ matrix.os }}.zip dist/vlmd.exe
    - name: Upload artifact (the zipped pyinstaller exe )
      uses: actions/upload-artifact@v3
      with:
        name: healdata-utils-${{ matrix.os }}
        path: healdata-utils-${{ matrix.os }}.zip
  
  # below steps taken from https://github.com/actions/upload-release-asset
  # NOTE: need write permissions for contents
  release:
    name: Create a release from a tag
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download artifacts (the zipped pyinstaller exe for each os)
        uses: actions/download-artifact@v3
      - name: Release with bundles
        uses: softprops/action-gh-release@v1
        with:
          files: |
            healdata-utils-windows-latest.zip
            healdata-utils-ubuntu-latest.zip
            healdata-utils-macos-latest.zip
