# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing Workflow

on:
  push:
    branches: [ "test-pipeline-deployment" ]
  pull_request:
    branches: [ "test-pipeline-deployment" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install pytest==7.3.2
        pip install .
    - name: Build Package
      run: |
        python -m build
    - name: Test with pytest
      run: |
        pytest
